---
version: "3"
services:
 application:
  image: admin_app
  networks:
   - pavaninet
  ports:
   - "8000:8000"
  depends_on:
   - mysqldb
 mysqldb: 
  image: mysql:5.7
  networks:
   - pavaninet
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: Categories
  volumes:
    - app_data:/var/lib/mysql
networks:
 pavaninet:
volumes:
 app_data:
...
